name: listinha
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uno: ^1.1.9
  result_dart: ^1.1.0
  flutter_modular: ^6.3.2
  realm: ^1.6.1
  intl: ^0.19.0
  rx_notifier: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.1
  flutterando_analysis: ^0.0.2

flutter:

  uses-material-design: true

  
